services:
    postgres:
        container_name: pg_container
        image: postgres:16-alpine
        ports:
            - "5433:5432"
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: eduJourney
        # volumes:
        #     - ./data:/var/lib/postgresql/data
        restart: always

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@admin.com
            - PGADMIN_DEFAULT_PASSWORD=admin
        # volumes:
        #     - ./pgadmin:/root/.pgadmin
        ports:
            - 5050:80

    juan-container:
        image: edujourney-backend
        container_name: eduJourney
        ports:
            - 8080:8080
        depends_on:
            - postgres
        restart: always